name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Checkout api
      - name: Checkout api
        uses: actions/checkout@v3
        with:
          repository: portfolio-api
          token: ${{ secrets.GH_PAT }}
          path: main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

        # Checkout client
      - name: Checkout client
        uses: actions/checkout@v3
        with:
          repository: portfolio
          token: ${{ secrets.GH_PAT }}
          path: main

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /portfolio
          NEXT_PUBLIC_SERVER_URL: https://bba369svpmm6ncl22bj6.containers.yandexcloud.net

      - name: Create .nojekyll file
        run: touch ./out/.nojekyll

      - name: Deploy application🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out # The folder the action should deploy.
