name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Checkout api
      - name: Checkout api
        uses: actions/checkout@v3
        with:
          repository: nukuutos/portfolio-api
          token: ${{ secrets.GH_PAT }}
          path: api

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: api/package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install api dependencies
        working-directory: ./api
        run: npm ci

      - name: Start api
        working-directory: ./api
        run: npm start &
        env:
          PORT: 5000
          NODE_ENV: test
          CLIENT_URL: http://localhost:3000

        # Checkout client
      - name: Checkout client
        uses: actions/checkout@v3
        with:
          repository: nukuutos/portfolio
          token: ${{ secrets.GH_PAT }}
          path: client

      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: Build client
        working-directory: ./client
        run: npm run build
        env:
          NEXT_PUBLIC_SERVER_URL: http://localhost:5000

      - name: Start client
        working-directory: ./client
        run: npm start &

      - name: Run cypress
        working-directory: ./client
        run: npm run cypress:run

      - name: Rebuild client with production environment variables
        working-directory: ./client
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /portfolio
          NEXT_PUBLIC_SERVER_URL: https://bba369svpmm6ncl22bj6.containers.yandexcloud.net

      - name: Create .nojekyll file
        run: touch ./client/out/.nojekyll

      - name: Deploy application🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          working-directory: ./client
          folder: out # The folder the action should deploy.
